Fix comma causing curl error
```
curl --connect-timeout 0,2 -sL -w \"%{http_code}\" http://
```
curl manpage:
```
       --connect-timeout <seconds>
              ...
              This option accepts decimal values. The decimal value needs to be  provided
              using  a  dot  (.)  as decimal separator - not the local version even if it
              might be using another separator.
```

```
Error detected while processing ~/.vim/plugged/vim-llama/plugin/vim_llama.vim[48]..function TestOllamaConnection:
line   12:
ERROR: IP/Port not reachable!
```